config/routes.rb
SynergyMobileBeta::Application.routes.draw do
  match 'rest/actuation/:uri/methods/:method' => 'rest#actuation', :constraints => {:uri => /.*/, :method => /.*/}

  match 'rest/subtypes/spaces' => 'rest#all_space_subtypes'
  match 'rest/subtypes/things' => 'rest#all_thing_subtypes'

  match 'rest/users/sign_up' => "rest#sign_up"
  match 'rest/users/all' => "rest#list_all_users"

  match 'rest/liveSynergy/:uri/add' => 'rest#add_existing_entity', :constraints => {:uri => /.*/}
  match 'rest/liveSynergy/:uri/delete' => "rest#delete_entity", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/public' => "rest#my_public_things", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/private' => "rest#my_private_things", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/all' => "rest#my_things", :constraints => {:uri => /.*/}

  match 'rest/:uri/spaces/public' => "rest#my_public_spaces", :constraints => {:uri => /.*/}
  match 'rest/:uri/spaces/private' => "rest#my_private_spaces", :constraints => {:uri => /.*/}
  match 'rest/:uri/spaces/all' => "rest#my_spaces", :constraints => {:uri => /.*/}

  match 'rest/spaces/public/all' => "rest#all_public_spaces"
  match 'rest/things/public/all' => "rest#all_public_things"

  match 'rest/test' => "rest#test"
  match 'rest/entities/create' => "rest#create_new_entity"
  match 'rest/triggers/create' => "rest#create_new_trigger"

  match 'rest/friends/all' => "rest#view_my_friends"

  match 'rest/liveSynergy/:uri' => 'rest#view', :constraints => {:uri => /.*/}

  match '/allfriends' => "friends#allfriends"
  match 'liveSynergy/:uri/add_livePulse' => "entities#add_livePulse", :constraints => {:uri => /.*/}, :via => :get
  match 'liveSynergy/:uri/add_livePulse' => "entities#create_livePulse", :constraints => {:uri => /.*/}, :via => :post

  match '/users/:uri/energy/hour/data' => "energy#user_hour_data", :constraints => {:uri => /.*/}
  match '/users/:uri/energy/hour' => "energy#userhour", :constraints => {:uri => /.*/}
  match '/:uri/energy/hour/data' => "energy#hour_data", :constraints => {:uri => /.*/}
  match '/userview/:uri' => "friends#view", :constraints => {:uri => /.*/}
  match '/:uri/energy/hour' => "energy#hour", :constraints => {:uri => /.*/}

  match 'liveSynergy/:uri/methods/turnOn' => "triggers#turned_on_dialog", :constraints => {:uri => /.*/}
  match 'sms/sent' => "triggers#sms_sent_dialog"
  match 'liveSynergy/msra/sms-gateway/methods/send' => "triggers#send_sms_index", :via => :get
  match 'liveSynergy/msra/sms-gateway/methods/send' => "triggers#send_sms", :via => :post
  match '/failure/actuation' => "triggers#failure_dialog", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/methods/turnOff' => "triggers#turned_off_dialog", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/onHumanEnter' => "triggers#onHumanEnter_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/onHumanExit' => "triggers#onHumanExit_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/methods/currentOccupancy' => "triggers#currentOccupancy", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri' => "entities#view", :constraints => {:uri => /.*/}
  match 'add/:uri' => "entities#view_added_dialog", :constraints => {:uri => /.*/}
  match 'addedThing' => "entities#view_added_new_thing_dialog"
  match 'addedSpace' => "entities#view_added_new_space_dialog"
  match 'friends/add/:uri' => "friends#view_added_dialog", :constraints => {:uri => /.*/}
  match 'friends/delete/:uri' => "friends#view_delete_dialog", :constraints => {:uri => /.*/}
  match 'deletefriend/:uri' => "friends#delete_friend", :constraints => {:uri => /.*/}, :via => :get
  match 'delete/:uri' => "entities#view_delete_dialog", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/delete/:id' => "triggers#view_delete_dialog", :constraints => {:id => /.*/}, :via => :get

  match 'triggers/add/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanEnter' => "triggers#onHumanEnter_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanEnter' => "triggers#onHumanEnter_create_trigger", :constraints => {:uri => /.*/}, :via =>:post
  match 'triggers/add/:uri/events/onHumanExit' => "triggers#onHumanExit_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanExit' => "triggers#onHumanExit_create_trigger", :constraints => {:uri => /.*/}, :via => :post
  match 'triggers/add/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_create_trigger", :constraints => {:uri => /.*/}, :via => :post

  match 'triggers/add/msra/sms-gateway/methods/send' => "triggers#send_sms_add_trigger", :via => :get
  match 'triggers/add/msra/sms-gateway/methods/send' => "triggers#send_sms_add_trigger_finalize", :via => :post

  match 'delete/:uri' => "entities#delete_entity", :constraints => {:uri => /.*/}, :via => :delete

  match 'triggers/show/:id' => 'triggers#show', :via => :get
  match 'triggers/edit/:id' => 'triggers#edit', :via => :get
  match 'triggers/edit/:id' => 'triggers#update', :via => :post
  match 'triggers/added' => "triggers#view_added_dialog"
  
  match 'add_friend' => 'friends#add_existing_friend', :via => :get
  match 'add_friend' => 'friends#create_existing_friend', :via => :post
  match 'friends' => 'friends#view_all_friends', :via => :get

  match 'add_thing' => 'entities#add_new_or_existing_thing_dialog', :via => :get
  match 'new_thing' => 'entities#new_thing', :via => :get
  match 'new_space' => 'entities#new_space', :via => :get
  match 'choose_containing_space' => 'entities#choose_containing_space', :via => :get
  match 'add_space' => 'entities#add_new_or_existing_space_dialog', :via => :get
  match 'entities/add_existing_thing' => 'entities#create_existing_thing', :via => :post
  match 'entities/add_existing_thing' => 'entities#add_existing_thing', :via => :get

  match 'entities/add_existing_space' => 'entities#create_existing_space', :via => :post
  match '/new_thing_created' => 'entities#new_thing_created', :via => :post
  match '/new_space_created' => 'entities#new_space_created', :via => :post
  match 'entities/add_existing_space' => 'entities#add_existing_space', :via => :get  
  
  match 'entities/add_new_thing' => 'entities#new_thing', :via => :get
  match 'entities/add_new_thing' => 'entities#create_new_thing', :via => :post
  
  match 'entities/add_new_space' => 'entities#new_space', :via => :get
  match 'entities/add_new_space' => 'entities#create_new_space', :via => :post
  
  match 'triggers/add' => 'triggers#add_new_trigger', :via => :get
  match 'triggers/add' => 'triggers#create_new_trigger', :via => :post
  

  match 'things/all' => 'entities#list_all_things', :via => :get
  match 'things/public' => 'entities#public_things', :via => :get
  match 'things/private' => 'entities#private_things', :via => :get
  match 'spaces/all' => 'entities#list_all_spaces', :via => :get
  match 'spaces/public' => 'entities#public_spaces', :via => :get
  match 'spaces/private' => 'entities#private_spaces', :via => :get
  match 'triggers/all' => 'triggers#index', :via => :get

  match 'entities/edit_thing/:id' => 'entities#edit_thing', :via => :get
  match 'entities/edit_space/:id' => 'entities#edit_space', :via => :get

 
  match 'entities/update_form_add_new_trigger' => 'entities#update_form_add_new_trigger'
  
  match 'map/coordinates' => 'map#coordinates'
  match 'friends/coordinates' => 'map#friends_coordinates'

  match 'entities/energy_things_spaces_friends_menu' => 'entities#energy_things_spaces_friends_menu'
  match 'energy/thing/:url' => 'energy#thing_energy'
  
  match 'map' => 'map#index'
  match 'map2' => 'map#index5'
  
  match 'energy/thing2/:url' => 'energy#thing_energy2'
  match 'energy/thing3/:url' => 'energy#thing_energy3'
 
  match 'energy/thing4/:url' => 'energy#thing_energy4'
  match 'energy/thing5/:url' => 'energy#thing_energy5'
  
  match 'home/menu' => 'home#menu', :via => :get
   

  
  
  devise_for :users, :stateless_token => true, :controllers => {:sessions => "sessions", :registrations => "registrations"} do
    match '/users/sign_up', :to => 'registrations#new'

    match '/users/sign_up/:liveLinkID', :to => 'registrations#new_liveLinkID'
  end

  

  root :to => "home#index"
  

end

app/models/entity.rb
class Entity
  include Mongoid::Document

  field :name, :type => String
  field :livePulseID, :type => String
  field :desc, :type => String
  field :uri, :type => String
  field :type, :type => String
  field :subtype, :type => String
  field :states
  field :methods
  field :events
  field :triggers, :type => Array
  field :ownership, :type => String
  field :ancestors, :type => Array
  field :parent, :type => String
  field :coordinates, :type => String
  field :dimensions, :type => String
  has_many :readings, :class_name => 'Energy'
  has_and_belongs_to_many :users, :class_name => 'User'
  
  @@ownershipTypes = Array["Private","Public"]

  before_validation do
    self.name = self.name.gsub(/\s+/, "-").gsub(/[^\w-]/, "-").downcase    
    self.livePulseID = self.livePulseID.upcase.gsub(/\s+/, "")
  end


  def self.ownershipTypes
    @@ownershipTypes
  end
  
  def deep_copy
    Marshal.load(Marshal.dump(self))
  end

  def self.all_spaces
    @allCurrentSpacesArray = Entity.where(:type => "space")
    @allCurrentSpaces = Array.new
    @allCurrentSpacesArray.each do |space|
      ancestors = space.ancestors
      path = ""
      ancestors.each do |ancestor|
        path = path + "/" + ancestor
      end
      path = path + "/" + space.name
      @allCurrentSpaces << path
    end
    return @allCurrentSpaces
  end
  def self.all_thing_types
    return Prototype.any_in(ancestors:['thing']).to_a.collect{|x| x.name}
  end
  def self.all_space_types
    return Prototype.any_in(ancestors:['space']).to_a.collect{|x| x.name}
  end
  validates_presence_of :name, :uri, :type, :subtype
  attr_accessible :name, :livePulseID, :desc, :uri, :type, :subtype, :states, :methods, :events, :triggers, :ownership, :ancestors, :parent, :coordinates, :dimensions
end

app/views/entities/add_livepulse.html.erb
<div data-role="page" id="mainpage">

	<div data-role="header">
	  <h1>New Space</h1>
	  <%= link_to 'Back', '#', {"class" => "ui-btn-left", "data-rel"=>"back", "data-icon"=>"arrow-l"} %>
	</div>

	<div data-role="content">


<%= form_for(:entity) do |f| %>
  <%= render 'shared/error_messages', :target => @entity %>
  <%= render 'fields_space', :f => f %>
  <div class="actions">
    <%= f.submit "Create"%>
  </div>
<% end %>


</div>

</div>

app/views/entities/add_new_or_existing_space_dialog.html.erb
<div data-role="page" id="mainpage" class="ui-page ui-body-c ui-page-active" style="min-height: 562px; ">
    <div data-role="header" data-theme="d" data-position="inline" class="ui-header ui-bar-d" role="banner">
    <h1 class="ui-title" tabindex="0" role="heading" aria-level="1">Add Synergy Space</h1>
		</div>

		<div data-role="content" data-theme="c" class="ui-content ui-body-c" role="main">
			<h1>Add Existing or New Space?</h1>
			<!-- <p>This is a regular page, styled as a dialog. To create a dialog, just link to a normal page and include a transition and <code>data-rel="dialog"</code> attribute.</p> -->
			<%= link_to entities_add_existing_space_path, {'data-role' => "button", 'data-theme' => "b", 'class' => "ui-btn ui-btn-corner-all ui-shadow ui-btn-up-b", 'data-ajax' => 'false'} do %><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Existing</span></span><% end %> 
		 	<%= link_to entities_add_new_space_path, {'data-ajax' => 'false', 'data-role'=>'button', 'data-theme'=>"c", 'class' => "ui-btn ui-btn-corner-all ui-shadow ui-btn-up-c"} do %> <span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">New</span></span><%end%>    
		</div>
	</div>

app/views/entities/add_new_or_existing_thing_dialog.html.erb
<div data-role="page" id="mainpage" class="ui-page ui-body-c ui-page-active" style="min-height: 562px; ">
    <div data-role="header" data-theme="d" data-position="inline" class="ui-header ui-bar-d" role="banner">
    <h1 class="ui-title" tabindex="0" role="heading" aria-level="1">Add Synergy Thing</h1>
		</div>

		<div data-role="content" data-theme="c" class="ui-content ui-body-c" role="main">
			<h1>Add Existing or New Thing?</h1>
			<!-- <p>This is a regular page, styled as a dialog. To create a dialog, just link to a normal page and include a transition and <code>data-rel="dialog"</code> attribute.</p> -->
			<%= link_to entities_add_existing_thing_path, {'data-role' => "button", 'data-theme' => "b", 'class' => "ui-btn ui-btn-corner-all ui-shadow ui-btn-up-b"} do %><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Existing</span></span><% end %> 
		 	<%= link_to entities_add_new_thing_path, {'data-ajax' => 'false', 'data-role'=>'button', 'data-theme'=>"c", 'class' => "ui-btn ui-btn-corner-all ui-shadow ui-btn-up-c"} do %> <span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">New</span></span><%end%>    
		</div>
	</div>

app/views/entities/add_new_trigger.html.erb
<div data-role="page" id="mainpage" data-theme='a'>

<div data-role="header">
  <h1>Add New Trigger</h1>
    <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left",  "data-icon"=>"home"} %>
</div>

<div data-role="content">
 <%= render 'shared/trigger_error_messages', :target => @trigger %>

 <%= form_for(:trigger) do |f| %>
	<h2 style="text-align: center;"> title: </h2> 
	<%= f.text_field :title %>

	<h2 style="text-align: center;"> when: </h2> 
        <%= f.select :triggering_entity, options_for_select(@entities, '0'), {:id => 'triggering_entity'}%> 

	<h2 style="text-align: center;"> does this: </h2> 
	<%= f.select :triggering, options_for_select([].insert(0, ["Select","0"]), '0'), {:id => 'triggering'} %> 
	
	<div id="args1"></div>

        <h2 style="text-align: center;"> make this: </h2> 
        <%= f.select :triggered_entity, options_for_select(@entities, '0'), {:id => 'triggered_entity'}%> 

	<h2 style="text-align: center;"> do this: </h2> 
	<%= f.select :triggered, options_for_select([].insert(0, ["Select","0"]), '0'), {:id => 'triggered'} %> 
	
	<div id="args2"></div>

        <h2 style="text-align: center;"> description </h2> 
  	<%= f.text_area :description, {:id => 'description'} %>

	<h2 style="text-align: center;"> and when you are ready: </h2> 
        <div class="actions">
           <%= f.submit "Create Trigger!", {'data-ajax' => false, 'data-theme' => 'e'} %>
        </div>
 <% end %>
</div>
</div>
<script type="text/javascript">
    $('#mainpage').live('pagecreate',function(event){
	$('select#trigger_triggering_entity').change( function() {
	    $.ajax({
	        type: 'POST',
		dataType: 'json',
		url: '/entities/update_form_add_new_trigger',
	        data: {'url': $(this).val()},
		success: (function(data) {
		    var events = data.events;
		    var options = '<option value="">Select An Event</option>';
		    for (var i = 0; i < events.length; i++) {
			options += '<option data-type="event" value="' + events[i].name + '">' + events[i].name + '</option>';
		    }		
                    var methods = data.methods;
                
                    for (var i = 0; i < methods.length; i++) {
			options += '<option data-type="method" value="' + methods[i].name + '">' + methods[i].name + '</option>';
                    }       
	
		    $('select#trigger_triggering').html(options).trigger('refresh');
		    $('select#trigger_triggering').change( function() { 
		        var name = $(this).attr('value');
			var argStr;
			switch(name){
			    case 'onHumanEnter':
				argStr = '<%= f.select :user, options_for_select(@friends, '0')%>';
			        break;
			    case 'onHumanExit':
				argStr = '<%= f.select :user, options_for_select(@friends, '0')%>';
	 	                break;
			    case 'send':
				argStr = '<%= f.select :user, options_for_select(@friends, '0')%>';
				break;
			} 
			$("div#args1").html(argStr).trigger('create');
		    });	
		})
	    });
	});
   });
</script>

app/views/entities/choose_type.html.erb
<div data-role="page" id="mainpage">

<div data-role="header">
  <h1>Add Existing Space</h1>
  <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left", "data-icon"=>"home"} %>
  <%= link_to 'Add New', entities_add_new_space_path, {"class" => "ui-btn-right", "data-icon"=>"plus"} %>
</div>
<h2 style='text-align: center;'>Select the containing space of entity:</h2>

<div data-role="content" class="ui-content filter-list" role="main">
<!-- When choice is chosen, add to user's list of items of interest. -->
<ul data-role="listview" data-filter="true" class="ui-listview" id="list">

  <div class="field" data-role="fieldcontain">
    Subtype<br />
    <%= f.collection_select :subtype, Entity.all_thing_types, :downcase, :titleize %>
  </div>

  	<% Entity.all_thing_types.each do |thing| %>
	<li>
          <%= link_to space, "/liveSynergy" + thing, {:id => '#', :class => 'ui-link-inherit'}%>
</li>
<% end %>
</ul>
</div>

<div data-role="footer" data-id="foo1" data-position="fixed" class="ui-footer ui-bar-a ui-footer-fixed fade ui-fixed-inline" role="contentinfo" style="top: 0px; ">
		<div data-role="navbar" class="ui-navbar ui-navbar-noicons" role="navigation">
			<ul class="ui-grid-b">
				<li class="ui-block-a"><a href="#" class="ui-state-persist ui-btn ui-btn-up-a" data-theme="a"><span class="ui-btn-inner"><span class="ui-btn-text">Attributes</span></span></a></li>
				<li class="ui-block-b"><a href="#" data-theme="e" class="ui-btn ui-btn-down-a ui-btn-up-a"><span class="ui-btn-inner"><span class="ui-btn-text">Type</span></span></a></li>
				<li class="ui-block-c"><a href="#" data-theme="a" class="ui-btn ui-btn-up-e"><span class="ui-btn-inner"><span class="ui-btn-text">Space Container</span></span></a></li>
			</ul>
		</div><!-- /navbar -->
	</div>
</div>

app/views/entities/list_all_spaces.html.erb
<div data-role="page" id="mainpage">

<div data-role="header">
  <h1>My Spaces</h1>
  <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left", "data-icon"=>"home"} %>
  <%= link_to 'Add', add_space_path, {"class" => "ui-btn-right", "data-icon" => "plus"} %>
        <div data-role="navbar">
                <ul>
<li><a href="/spaces/all" class="ui-btn-active">All</a></li>

                        <li><a href="/spaces/public">Public</a></li>
                        <li><a href="/spaces/private">Private</a></li>
                </ul>
        </div><!-- /navbar -->

</div>
<div data-role="content" class="ui-content" role="main">
<% if not @hash.empty? %>
<div class='filter-list'>
<ul data-role="listview" data-filter="true" class="ui-listview" id="list">
<% @hash.keys.each do |subtype| %>
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-a"><%= subtype %> </li>
  	<% @hash[subtype].each do |space| %>
	<li>
          <%= link_to space, "/liveSynergy" + space, {:id => '#', :class => 'ui-link-inherit', 'data-theme' => 'e'}%>
          <%= link_to 'Delete', "/delete" + space, "data-icon" => "minus", 'data-theme' => 'e'%>
	<% end %>
	<% end %>
</ul>
</div>
<% else %>
<h2>  Please add a space to your collection! </h2>
<% end %>
</div>

</div>

app/views/entities/list_all_things.html.erb
<div data-role="page" id="mainpage">

<div data-role="header">
  <h1>My Things</h1>
  <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left", "data-icon"=>"home"} %>
  <%= link_to 'Add New', add_thing_path, {"class" => "ui-btn-right", "data-icon" => "plus"} %>
        <div data-role="navbar">
                <ul>
<li><a href="/things/all" class="ui-btn-active">All</a></li>

                        <li><a href="/things/public">Public</a></li>
                        <li><a href="/things/private">Private</a></li>
                </ul>
        </div><!-- /navbar -->

</div>
<div data-role="content" class="ui-content" role="main">
<% if not @hash.empty? %>
<div class="filter-list">
<ul data-role="listview" data-filter="true" class="ui-listview" id="list">
<% @hash.keys.each do |subtype| %>
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-a"><%= subtype %> </li>
  	<% @hash[subtype].each do |thing| %>
	<li>
          <%= link_to thing, "/liveSynergy" + thing, {:id => '#', :class => 'ui-link-inherit', 'data-theme' => 'e'}%>
          <%= link_to 'Delete', "/delete" + thing, "data-icon" => "minus", 'data-theme' => 'e' %>
	<% end %>
	<% end %>
</ul>
</div>
<% else %>
<h2>  Please add a thing to your collection! </h2>
<% end %>
</div>

</div>

app/views/entities/private_spaces.html.erb
<div data-role="page" id="mainpage">

<div data-role="header">
  <h1>My Spaces</h1>
  <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left", "data-icon"=>"home"} %>
  <%= link_to 'Add', add_space_path, {"class" => "ui-btn-right", "data-icon" => "plus"} %>
        <div data-role="navbar">
                <ul>
<li><a href="/spaces/all">All</a></li>

                        <li><a href="/spaces/public">Public</a></li>
                        <li><a href="/spaces/private" class="ui-btn-active">Private</a></li>
                </ul>
        </div><!-- /navbar -->

</div>
<div data-role="content" class="ui-content" role="main">
<% if not @hash.empty? %>
<div class='filter-list'>
<ul data-role="listview" data-filter="true" class="ui-listview" id="list">
<% @hash.keys.each do |subtype| %>
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-a"><%= subtype %> </li>
  	<% @hash[subtype].each do |space| %>
	<li>
          <%= link_to space, "/liveSynergy" + space, {:id => '#', :class => 'ui-link-inherit', 'data-theme' => 'e'}%>
          <%= link_to 'Delete', "/delete" + space, "data-icon" => "minus", 'data-theme' => 'e'%>
	<% end %>
	<% end %>
</ul>
</div>
<% else %>
<h2>  Please add a space to your collection! </h2>
<% end %>
</div>

</div>

app/views/entities/private_things.html.erb
<div data-role="page" id="mainpage">

<div data-role="header">
  <h1>My Things</h1>
  <%= link_to 'Home', home_menu_path, {"class" => "ui-btn-left", "data-icon"=>"home"} %>
  <%= link_to 'Add New', add_thing_path, {"class" => "ui-btn-right", "data-icon" => "plus"} %>
        <div data-role="navbar">
                <ul>
<li><a href="/things/all">All</a></li>

                        <li><a href="/things/public">Public</a></li>
                        <li><a href="/things/private" class="ui-btn-active">Private</a></li>
                </ul>
        </div><!-- /navbar -->

</div>
<div data-role="content" class="ui-content" role="main">
<% if not @hash.empty? %>
<div class="filter-list">
<ul data-role="listview" data-filter="true" class="ui-listview" id="list">
<% @hash.keys.each do |subtype| %>
	<li data-role="list-divider" role="heading" class="ui-li ui-li-divider ui-btn ui-bar-a"><%= subtype %> </li>
  	<% @hash[subtype].each do |thing| %>
	<li>
          <%= link_to thing, "/liveSynergy" + thing, {:id => '#', :class => 'ui-link-inherit', 'data-theme' => 'e'}%>
          <%= link_to 'Delete', "/delete" + thing, "data-icon" => "minus", 'data-theme' => 'e' %>
	<% end %>
	<% end %>
</ul>
</div>
<% else %>
<h2>  Please add a thing to your collection! </h2>
<% end %>
</div>
</div>

app/views/entities/show_space.html.erb
<div data-role="page">

<div data-role="header">
  <h1>Space - Attributes</h1>
  <%= link_to 'Back', '#', {"class" => "ui-btn-left", "data-rel"=>"back", "data-icon"=>"arrow-l"} %>
  <%= link_to 'Add', entities_add_new_space_path, "data-role" => "button", "data-icon" => "plus", "class" => "ui-btn-right", "id" => "add-button" %>
  <!-- # add javascript here to pull up dialog.... -->
</div>
<div data-role="content">
	<table summary="This table lists all the JetBlue flights.">
	  <!-- <caption>Travel Itinerary</caption> -->
	  <!-- <thead>
	    <tr>
	       <th scope="col">Flight:</th>  
	      <th scope="col">From:</th>  
	      <th scope="col">To:</th>  
	    </tr>
	  </thead> -->
	<tbody>
	  <tr>
	    <th scope="col">Name:</th>
	    <td><%=@entity.name%></td>
	  </tr>
	  <tr>
	    <th scope="col">livePulseID:</th>
	    <td><%=@entity.livePulseID%></td>
	  </tr>
	  <tr>
	    <th scope="col">Type:</th>
	    <td><%=@entity.type%></td>
	  </tr>
	  <tr>
	    <th scope="col">Methods:</th>
	    <td><%=@entity.methods%></td>
	  </tr>
	  <tr>
	    <th scope="col">Events:</th>
	    <td><%=@entity.events%></td>
	  </tr>
	</tbody>
	  <!-- <tfoot>
	    <tr>
	      <td colspan="5">Total: 3 flights</td>
	    </tr>
	  </tfoot> -->
	</table>
</ul>
</div>

</div>
<p id="notice"><%= notice %></p>