config/routes.rb
SynergyMobileBeta::Application.routes.draw do
  match 'rest/actuation/:uri/methods/:method' => 'rest#actuation', :constraints => {:uri => /.*/, :method => /.*/}

  match 'rest/subtypes/spaces' => 'rest#all_space_subtypes'
  match 'rest/subtypes/things' => 'rest#all_thing_subtypes'

  match 'rest/users/sign_up' => "rest#sign_up"
  match 'rest/users/all' => "rest#list_all_users"

  match 'rest/liveSynergy/:uri/add' => 'rest#add_existing_entity', :constraints => {:uri => /.*/}
  match 'rest/liveSynergy/:uri/delete' => "rest#delete_entity", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/public' => "rest#my_public_things", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/private' => "rest#my_private_things", :constraints => {:uri => /.*/}
  match 'rest/:uri/things/all' => "rest#my_things", :constraints => {:uri => /.*/}

  match 'rest/:uri/spaces/public' => "rest#my_public_spaces", :constraints => {:uri => /.*/}
  match 'rest/:uri/spaces/private' => "rest#my_private_spaces", :constraints => {:uri => /.*/}
  match 'rest/:uri/spaces/all' => "rest#my_spaces", :constraints => {:uri => /.*/}

  match 'rest/spaces/public/all' => "rest#all_public_spaces"
  match 'rest/things/public/all' => "rest#all_public_things"

  match 'rest/test' => "rest#test"
  match 'rest/entities/create' => "rest#create_new_entity"
  match 'rest/triggers/create' => "rest#create_new_trigger"

  match 'rest/friends/all' => "rest#view_my_friends"

  match 'rest/liveSynergy/:uri' => 'rest#view', :constraints => {:uri => /.*/}

  match '/allfriends' => "friends#allfriends"
  match 'liveSynergy/:uri/add_livePulse' => "entities#add_livePulse", :constraints => {:uri => /.*/}, :via => :get
  match 'liveSynergy/:uri/add_livePulse' => "entities#create_livePulse", :constraints => {:uri => /.*/}, :via => :post

  match '/users/:uri/energy/hour/data' => "energy#user_hour_data", :constraints => {:uri => /.*/}
  match '/users/:uri/energy/hour' => "energy#userhour", :constraints => {:uri => /.*/}
  match '/:uri/energy/hour/data' => "energy#hour_data", :constraints => {:uri => /.*/}
  match '/userview/:uri' => "friends#view", :constraints => {:uri => /.*/}
  match '/:uri/energy/hour' => "energy#hour", :constraints => {:uri => /.*/}

  match 'liveSynergy/:uri/methods/turnOn' => "triggers#turned_on_dialog", :constraints => {:uri => /.*/}
  match 'sms/sent' => "triggers#sms_sent_dialog"
  match 'liveSynergy/msra/sms-gateway/methods/send' => "triggers#send_sms_index", :via => :get
  match 'liveSynergy/msra/sms-gateway/methods/send' => "triggers#send_sms", :via => :post
  match '/failure/actuation' => "triggers#failure_dialog", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/methods/turnOff' => "triggers#turned_off_dialog", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/onHumanEnter' => "triggers#onHumanEnter_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/events/onHumanExit' => "triggers#onHumanExit_index", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri/methods/currentOccupancy' => "triggers#currentOccupancy", :constraints => {:uri => /.*/}
  match 'liveSynergy/:uri' => "entities#view", :constraints => {:uri => /.*/}
  match 'add/:uri' => "entities#view_added_dialog", :constraints => {:uri => /.*/}
  match 'addedThing' => "entities#view_added_new_thing_dialog"
  match 'addedSpace' => "entities#view_added_new_space_dialog"
  match 'friends/add/:uri' => "friends#view_added_dialog", :constraints => {:uri => /.*/}
  match 'friends/delete/:uri' => "friends#view_delete_dialog", :constraints => {:uri => /.*/}
  match 'deletefriend/:uri' => "friends#delete_friend", :constraints => {:uri => /.*/}, :via => :get
  match 'delete/:uri' => "entities#view_delete_dialog", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/delete/:id' => "triggers#view_delete_dialog", :constraints => {:id => /.*/}, :via => :get

  match 'triggers/add/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanEnter' => "triggers#onHumanEnter_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanEnter' => "triggers#onHumanEnter_create_trigger", :constraints => {:uri => /.*/}, :via =>:post
  match 'triggers/add/:uri/events/onHumanExit' => "triggers#onHumanExit_add_trigger", :constraints => {:uri => /.*/}, :via => :get
  match 'triggers/add/:uri/events/onHumanExit' => "triggers#onHumanExit_create_trigger", :constraints => {:uri => /.*/}, :via => :post
  match 'triggers/add/:uri/events/whenNumOccupancyReachesX' => "triggers#whenNumOccupancyReachesX_create_trigger", :constraints => {:uri => /.*/}, :via => :post

  match 'triggers/add/msra/sms-gateway/methods/send' => "triggers#send_sms_add_trigger", :via => :get
  match 'triggers/add/msra/sms-gateway/methods/send' => "triggers#send_sms_add_trigger_finalize", :via => :post

  match 'delete/:uri' => "entities#delete_entity", :constraints => {:uri => /.*/}, :via => :delete

  match 'triggers/show/:id' => 'triggers#show', :via => :get
  match 'triggers/edit/:id' => 'triggers#edit', :via => :get
  match 'triggers/edit/:id' => 'triggers#update', :via => :post
  match 'triggers/added' => "triggers#view_added_dialog"
  
  match 'add_friend' => 'friends#add_existing_friend', :via => :get
  match 'add_friend' => 'friends#create_existing_friend', :via => :post
  match 'friends' => 'friends#view_all_friends', :via => :get

  match 'add_thing' => 'entities#add_new_or_existing_thing_dialog', :via => :get
  match 'new_thing' => 'entities#new_thing', :via => :get
  match 'new_space' => 'entities#new_space', :via => :get
  match 'choose_containing_space' => 'entities#choose_containing_space', :via => :get
  match 'add_space' => 'entities#add_new_or_existing_space_dialog', :via => :get
  match 'entities/add_existing_thing' => 'entities#create_existing_thing', :via => :post
  match 'entities/add_existing_thing' => 'entities#add_existing_thing', :via => :get

  match 'entities/add_existing_space' => 'entities#create_existing_space', :via => :post
  match '/new_thing_created' => 'entities#new_thing_created', :via => :post
  match '/new_space_created' => 'entities#new_space_created', :via => :post
  match 'entities/add_existing_space' => 'entities#add_existing_space', :via => :get  
  
  match 'entities/add_new_thing' => 'entities#new_thing', :via => :get
  match 'entities/add_new_thing' => 'entities#create_new_thing', :via => :post
  
  match 'entities/add_new_space' => 'entities#new_space', :via => :get
  match 'entities/add_new_space' => 'entities#create_new_space', :via => :post
  
  match 'triggers/add' => 'triggers#add_new_trigger', :via => :get
  match 'triggers/add' => 'triggers#create_new_trigger', :via => :post
  

  match 'things/all' => 'entities#list_all_things', :via => :get
  match 'things/public' => 'entities#public_things', :via => :get
  match 'things/private' => 'entities#private_things', :via => :get
  match 'spaces/all' => 'entities#list_all_spaces', :via => :get
  match 'spaces/public' => 'entities#public_spaces', :via => :get
  match 'spaces/private' => 'entities#private_spaces', :via => :get
  match 'triggers/all' => 'triggers#index', :via => :get

  match 'entities/edit_thing/:id' => 'entities#edit_thing', :via => :get
  match 'entities/edit_space/:id' => 'entities#edit_space', :via => :get

 
  match 'entities/update_form_add_new_trigger' => 'entities#update_form_add_new_trigger'
  
  match 'map/coordinates' => 'map#coordinates'
  match 'friends/coordinates' => 'map#friends_coordinates'

  match 'entities/energy_things_spaces_friends_menu' => 'entities#energy_things_spaces_friends_menu'
  match 'energy/thing/:url' => 'energy#thing_energy'
  
  match 'map' => 'map#index'
  match 'map2' => 'map#index5'
  
  match 'energy/thing2/:url' => 'energy#thing_energy2'
  match 'energy/thing3/:url' => 'energy#thing_energy3'
 
  match 'energy/thing4/:url' => 'energy#thing_energy4'
  match 'energy/thing5/:url' => 'energy#thing_energy5'
  
  match 'home/menu' => 'home#menu', :via => :get
   

  
  
  devise_for :users, :stateless_token => true, :controllers => {:sessions => "sessions", :registrations => "registrations"} do
    match '/users/sign_up', :to => 'registrations#new'

    match '/users/sign_up/:liveLinkID', :to => 'registrations#new_liveLinkID'
  end

  

  root :to => "home#index"
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      render 'menu' 
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div data-role="page">


<div data-role="header">
      <h1><%= @title || 'Synergy' %></h1>
      <% unless user_signed_in? %>
        <%= link_to 'Sign In', new_user_session_path, "class" => "ui-btn-right" %>
      <% else %>
        <%= link_to 'Sign Out', destroy_user_session_path, "class" => "ui-btn-right" %>
      <% end %>
</div>
<div data-role="content">
<p>To enable richer and more efficient interactions with their environment,
humans need real-time fine-grained knowledge
and control over physical objects, and the environment needs
to be aware of humans and make intelligent decisions. To
facilitate this, we propose an architecture composed of three
parts – an accurate indoor localization primitive, a reliable
IPv6 based networking layer, and an event-based, hierarchical
virtual object overlay. We design and evaluate a system
that provides real-time and precise indoor human localization
using magnetic induction. Wireless mobile nodes
(LiveLinks) are used to detect dynamic magnetic fields generated
by beacons (LivePulses) for localization. We show
that, by building upon this primitive, we are able to augment
physical devices with additional services in the virtual
overlay to enable richer interaction between humans and objects.
Finally, we evaluate our system with a “personal energy
footprint” application that tracks individuals’ real-time
energy usage. </p>
<%= link_to new_user_registration_path, {"data-role"=>"button","data-theme"=>"e","class"=>"ui-btn ui-btn-corner-all ui-shadow ui-btn-down-e ui-btn-up-e"} do %>
<span class='ui-btn-inner ui-btn-corner-all'><span class='ui-btn-text'>Join Now</span></span>
<% end %>


</div>

</div>

app/views/home/menu.html.erb
<div data-role="page" id="mainpage">
		<div data-role="header" data-theme='a'>
			<h1>
				Welcome <%= current_user.name %>
			</h1><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => "ui-btn-right" %>
		</div>
		<div data-role="content">
			<ul data-role="listview" data-inset="true" data-theme="d" data-dividertheme="d">
				<li data-role="list-divider">Browse My Collection
				</li>
				<li>                                      
					<%= link_to 'My Spaces',  spaces_all_path%>
					<span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= current_user.spaces.length %> </span>	
				</li>
				<li>
					<%= link_to 'My Things',  things_all_path%>
					<span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= current_user.things.length %> </span>	
				</li>                                     
	
				<li>                                      
					<%= link_to 'My Triggers',  triggers_all_path%>
					<span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= current_user.triggers.length %> </span>	
				</li>
				<li>                                      
					<%= link_to 'My Friends',  friends_path, {'data-ajax' => 'false'}%>
					<span class="ui-li-count ui-btn-up-c ui-btn-corner-all"><%= (current_user.friends.length - 1)%> </span>	
				</li>
			</ul>
			<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="d">
				<li data-role="list-divider">Add
				</li>
				<li>                                      
					<%= link_to 'Space', add_space_path%>
				</li>                                     
				<li>
					<%= link_to 'Thing', add_thing_path%>
				</li> 



				<li>                                      
					<%= link_to 'Trigger', triggers_add_path, {'data-ajax' => 'false'}%>
				</li>
				<li>                                      
					<%= link_to 'Friend', add_friend_path%>
				</li>
			<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="d">
				<li data-role="list-divider">Visualizations
				</li>
				<li>

					<%= link_to 'Energy [Beta]', entities_energy_things_spaces_friends_menu_path %>
				</li>
				<li>
					<%= link_to 'Live Location [Beta]', map_path  %>
				</li>
			</ul>			
				<ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="d">

				<li data-role="list-divider">Preferences
				</li>
				<li>

					<%= link_to 'Change My Settings', edit_user_registration_path %>
				</li>
			</ul>

		</div>
</div>